### ISSUE TITLE
RSV code is always firing false.

### ISSUE THREAD

**Issue by Pet-Slime** [drbirbdev/StardewValley#5] opened 2023-03-01 11:22 UTC
`        public static bool Prepare()
        {
            return ModEntry.RSVLoaded;
        }`

This always seems to be returning false. I noticed it when I had EXP bars and wasn't gaining exp in ridgeside... and villagers weren't getting angry at me. 

Downloading the github here and removing that code, seemed to fix it. That said, removing that without having ridgeside village installed might cause issues.

**Comment by drbirbdev** [comment] 2023-04-23 00:49
This is fixed now (by chance)

```
 private void Event_GameLaunched(object sender, GameLaunchedEventArgs e)
        {
            new ConfigClassParser(this, Config).ParseConfigs();
            new Harmony(this.ModManifest.UniqueID).PatchAll();
            new CommandClassParser(this.Helper.ConsoleCommands, new Command()).ParseCommands();

            RSVLoaded = this.Helper.ModRegistry.IsLoaded("Rafseazz.RidgesideVillage");
            AutomateLoaded = this.Helper.ModRegistry.IsLoaded("Pathoschild.Automate");
            JALoaded = this.Helper.ModRegistry.IsLoaded("spacechase0.JsonAssets");
            DGALoaded = this.Helper.ModRegistry.IsLoaded("spacechase0.DynamicGameAssets");
            MargoLoaded = this.Helper.ModRegistry.IsLoaded("DaLion.Overhaul");
```

Harmony patching was being called before these booleans were set.  Since I refactored out those booleans, the problem is gone now.

**Closed by drbirbdev** 2023-04-23 00:49 UTC
